name: Test Suite

on:
  pull_request:
    types: [opened, synchronize, ready_for_review]

jobs:
  test-suite:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24.1"

      - name: Install dependencies
        run: go mod download

      - name: Run tests
        run: make test

      - name: Build
        run: make build

      - name: Check formatting
        run: |
          # Run go fmt to reformat code
          make fmt
          # If there are any changes, show an error and exit non-zero.
          if [ -n "$(git diff)" ]; then
            echo "Code is not properly formatted. Please run 'make fmt' to fix formatting."
            exit 1
          fi
